### ISSUE TITLE
cdm_reader_mapper fails to install (snappy)

### ISSUE THREAD

**Issue by jtsiddons** [glamod/cdm_reader_mapper#33]
`cdm_reader_mapper` fails to install with the following error

```
ERROR: Could not find a version that satisfies the requirement snappy<1.2 (from cdm-reader-mapper) (from versions: 2.2, 2.3, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.5, 2.5.1, 2.5.2, 2.5.4, 2.6, 2.6.1.post1, 2.7, 2.8, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.1, 3.1.1)
ERROR: No matching distribution found for snappy<1.2
```

(or similar depending on python version). The failure is from the dependency `snappy`.

Steps to reproduce:

```
docker run --rm -it python:3.11-slim-bookworm bash
apt update
apt install git gcc
git clone https://github.com/glamod/cdm_reader_mapper.git cdm_reader_mapper
cd cdm_reader_mapper
python -m venv venv
source ./venv/bin/activate
pip install .
```

I have tested this with python versions 3.9.12, 3.11.9, and 3.12.3. All get similar errors (referencing `ERROR: No matching distribution found for snappy<1.2`).

**Comment by ludwiglierhammer** [comment]
@jtsiddons: I added snappy to the requirements because of this [issue](https://github.com/openforcefield/openff-nagl/issues/106). Unforunately, you can install `snappy<1.2` with conda but not with pip. In the meantime I think the issue was closed. Thus we can abstain from `snappy<1.2`.

Would you please make a new PR and test the installation and the code without `snappy` in the requirements. I hope `cdm_reader_mapper` runs without `snappy` as a dependency.

**Comment by ludwiglierhammer** [comment]
[`snappy` on pip](https://pypi.org/project/snappy/) is not the [`snappy` we need](https://anaconda.org/conda-forge/snappy). There is an [old `snappy` version (0.7.1)](https://pypi.org/project/python-snappy/) on pip called `python-snappy`.

**Comment by ludwiglierhammer** [comment]
Many thanks for this bug fix.
